### ISSUE TITLE
Identify the table schemas that needs to be created for KnolShare

### ISSUE THREAD

**Issue by SangeetaGulia** [knoldus/cc-KnolShare#4]
Parent :  #1

**Comment by shivangi1015** [comment]
Identified schemas are: 
 1. User(id: Int, userName: String, email: String, password: String,phone_num: String)
2. Admin(id: Int, email: String, password: String)
3. KnolxSession(id: Int, presentor: String, topic: Option[String], session_id: Option[Int], rating: Option[Int], scheduledDate: Date)
4. Video_Store(presentor: String, topic: String, video_url: String, rating: Int, id: Int)
